objects/Contact/fields/External_System_ID__c.field-meta.xml
<CustomField>
    <fullName>External_System_ID__c</fullName>
    <description>This field is created as part of Assignment, 
This will uniquely Identify a Contact in an External system,
Will be using it in ProductInformationREST Apex class</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External System ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This picklist will hold the 2 Digit Country Codes</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This picklist is used to put the Product name, It Also will be used to match the Information from the Product Information table.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>This Object will hold the information about the Product and Countries</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI_{000}</displayFormat>
        <label>Product_Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This will Hold the 2 Digit Country Code, we will be having the same type of Field be present on Contact so that we can match the records.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field will be used to Hold the Product name.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

classes/ProductInformationREST_Test.cls
/*
Author: Amir Shahzad
On 2nd November, 2019
Build this Class as part of the Case study assignment
This is the Test coverage class for the class ProductInformationController
*/
@isTest 
public class ProductInformationREST_Test {
    static testMethod void VerifyProductInfoByContact() {

        Account acc = OrgTestDataFectory.PrepareAccount();   
        insert acc;        //insert Account
        
        Contact con = OrgTestDataFectory.PrepareContact(acc.Id);
        con.Home_Country__C = 'UK';
        con.Product__C = 'Standard';
        con.External_System_ID__c = 'ID001Ext01';
        insert con;        //insert Contact
        
        Product_Information__c ObjProdInfo = OrgTestDataFectory.PrepareProductInfo();
        insert ObjProdInfo; // Insert Product Information

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
//Set the REST request with Parameter
        req.requestURI = '/services/apexrest/Productinfo'; 
        req.addParameter('ExtID', 'ID001Ext01');
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
//Call the REST Get Enabled function
        ProductInformationREST.getProductInfo();

    }
}