objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This picklist will hold the 2 Digit Country Codes</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This picklist is used to put the Product name, It Also will be used to match the Information from the Product Information table.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>This Object will hold the information about the Product and Countries</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI_{000}</displayFormat>
        <label>Product_Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Information__c/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <description>This will Hold the actual Charges information
This could have been a Currency field, but the Nature of Data shown in the sample tables in the assignment requires it to be text. e.g. € 9,90 N/a , Free and 1.7%</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Charges</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This will Hold the 2 Digit Country Code, we will be having the same type of Field be present on Contact so that we can match the records.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field will be used to Hold the Product name.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/fields/Type_of_Charges__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Charges__c</fullName>
    <description>This Picklist will hold the Type of Charges</description>
    <label>Type of Charges</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Fee in other currencies</fullName>
            </value>
            <value>
                <fullName>Card Replacement Cost</fullName>
            </value>
            <value>
                <fullName>Cost per Calendar Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ProductInformationController.cls
/*
Author: Amir Shahzad
On 2nd November, 2019
Build this Class as part of the Case study assignment
*/
public with sharing class ProductInformationController {
//This method needs to be AURA Enabled, as this will be Called from LWC "ProductInformaiton"    
 @AuraEnabled(cacheable=true)
    public static List<Product_Information__c> findRelatedProductInfo (Id recordId) {
        List<Product_Information__c> lprodInfo = New List<Product_Information__c>();
         Case thisCase = [Select Id, ContactId, Contact.Product__c, Contact.Home_Country__c from Case where Id=: recordId];
         if(thisCase!=null)
                lprodInfo = [SELECT Name, Type_of_Charges__c, Product__c, Home_Country__c, Charges__c FROM Product_Information__c where Product__c= :thisCase.Contact.Product__c  And Home_Country__C = :thisCase.Contact.Home_Country__C Order by Type_of_Charges__c];
         return lprodInfo;
     }
}