objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This picklist will hold the 2 Digit Country Codes</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This picklist is used to put the Product name, It Also will be used to match the Information from the Product Information table.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>This Object will hold the information about the Product and Countries</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI_{000}</displayFormat>
        <label>Product_Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Information__c/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <description>This will Hold the actual Charges information
This could have been a Currency field, but the Nature of Data shown in the sample tables in the assignment requires it to be text. e.g. € 9,90 N/a , Free and 1.7%</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Charges</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This will Hold the 2 Digit Country Code, we will be having the same type of Field be present on Contact so that we can match the records.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field will be used to Hold the Product name.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Information__c/fields/Type_of_Charges__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Charges__c</fullName>
    <description>This Picklist will hold the Type of Charges</description>
    <label>Type of Charges</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Fee in other currencies</fullName>
            </value>
            <value>
                <fullName>Card Replacement Cost</fullName>
            </value>
            <value>
                <fullName>Cost per Calendar Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/OrgTestDataFectory.cls
/*
Author: Amir Shahzad
On 2nd November, 2019
Build this Class as part of the Case study assignment
This is class is used to create test records
*/
@isTest 
public class OrgTestDataFectory {

    Public static Account PrepareAccount()
    {
         Account a = new Account();            
            a.Name = 'TestProdUserCount';            
            a.BillingStreet = '1 Road';            
            a.BillingCity = 'City';           
            a.BillingCountry = 'France';            
            a.BillingPostalCode = '11501';
            a.CurrencyIsoCode='USD';  
         return a;  
       }
    
    Public static Contact PrepareContact(ID accId)
    {      
        //Prepare a contact, 
        Contact c = new Contact();
            c.AccountId = accId;
            c.FirstName = 'Test';
            c.LastName = 'ProdUserCount';
            c.Email = 'PUtest@test.com';
        return c;      
    }
    public static Case  PrepareCase(ID contId)
    {
        //Prepare the Case
        Case myCase = new Case();
            myCase.Subject = 'Test Subject';
            myCase.Status = 'New';
            myCase.Description = 'Test Description';
            myCase.Subject = 'My Test Subject';
            myCase.ContactId = contId;
            myCase.Support_Type__c = 'Data Collection';
            myCase.Business_Impact__c = 'Information/Enhancement Request';
            myCase.Application__c = 'New Salesforcce User Required';
            myCase.Functional_Area__c = 'Accounts';
        return myCase;
    }
    public static Product_Information__c PrepareProductInfo()
    {
        //Prepare the Product Information
        Product_Information__c PI = New Product_Information__c();
            PI.Home_Country__C = 'UK';
            PI.Product__C = 'Standard';
            PI.Type_of_Charges__c = 'Cost per Calendar Month';
            PI.Charges__c = '100.75';
        return PI;
    }
    
}